### ISSUE TITLE
Update docs to include "Snapshots cannot be greater than 16MB"

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#109]
@scullxbones I ran into a problem with persisting a snapshot greater than 16MB which exceeds the maximum document size of mongodb.

mongodg.log:
```
2016-04-07T15:12:01.093+0200 [conn96] Assertion: 10334:BSONObj size: 16793987 (0x1004183) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "snapshot"
```

I currently use 

`"com.github.scullxbones"     %%  "akka-persistence-mongo-rxmongo" % "0.4.1"`

Is this solved with a newer version of akka-persistence-mongo already?

**Comment by scullxbones** [comment]
Hi @marcuslinke -

Wow, that's a big snapshot.

No, there's no handling for a snapshot that's > 16MB in a later release.

**Comment by marcuslinke** [comment]
@scullxbones Would it be possible to fix this by splitting the snapshot into pieces?

**Comment by marcuslinke** [comment]
...or maybe snapshots should be stored in GridFS?

**Comment by scullxbones** [comment]
I'd be open to a pull request on this, but it needs to be strictly opt-in by configuration.  For both of the suggestions (multi-doc split or GridFS) the operations are no longer atomic, which is quite a trade-off.

**Comment by marcuslinke** [comment]
I think because snapshots are optimizations only this doesn't really matter. Or are there other implications?

**Comment by scullxbones** [comment]
Optimizations is one use case, but it's not uncommon that applications delete the journal entries with sequence numbers less than the snapshot.  In that case there'd be no recovery in case of a partial write.

Let's ignore the atomicity for a minute.  It's a more complicated approach.  As a user of the plugin myself, I'd prefer not to add complexity to my code path that I don't need.  I don't think this is that unusual of a position for a library user to have.  That's why I'd need any PR to require configuration opt-in.

**Comment by marcuslinke** [comment]
Thanks for your suggestions. Personally I'm sure now I can workaround the limitation by removing state out of the persistent actor into a special view model. So you may close this issue or keep it open for others to know. Maybe this limitation should be documented somewhere in the docs.

**Comment by scullxbones** [comment]
Sure thing.  I updated the title of the ticket to reflect adding this bit of info to the docs.

**Comment by scullxbones** [comment]
Docs added to `akka23.md` and `akka24.md`.  Thanks for the report!
