### ISSUE TITLE
Plugin creates a capped collection without index on _id

### ISSUE THREAD

**Issue by barakbn** [scullxbones/akka-persistence-mongo#167]
Hi,

We were getting this error message:

> Server has startup warnings:
> 2017-09-11T10:59:04.751+0000 I STORAGE  [initandlisten] WARNING: the collection '<DB name>.<realtime-collection name>' lacks a unique index on _id. This index is needed for replication to function properly

And indeed, our realtime-collection lacks an index on _id. 

I believe the reason is the  cappedCollection method in RxMongoDriver:
```

override private[mongodb] def cappedCollection(name: String)(implicit ec: ExecutionContext) = {
    collection(name).flatMap { cc =>
      cc.stats().flatMap { s =>
        if (!s.capped) cc.convertToCapped(realtimeCollectionSize, None)
        else Future.successful(())
      }.recoverWith {
        case _ => cc.createCapped(realtimeCollectionSize, None)
      }.map(_ => cc)
    }
  }

```
taken from: [https://github.com/scullxbones/akka-persistence-mongo/blob/789da6ea06c64cf3234d7b0317b025ec33114906/rxmongo/src/main/scala/akka/contrib/persistence/mongodb/RxMongoPersistenceExtension.scala](url)

If the capped collection does not already exist,  the plugin will try to create it using CollectionMetaCommands#createCapped method. However,  createCapped (by default) does not create an index on _id: 

```  
def createCapped(size: Long, maxDocuments: Option[Int], autoIndexId: Boolean = false)(implicit ec: ExecutionContext): Future[Unit] =
    Command.run(BSONSerializationPack).unboxed(
      self,
      Create(Some(Capped(size, maxDocuments)), autoIndexId),
      ReadPreference.primary
    )
```

Is this a bug or is it by-design (maybe because of performance considerations)?

**Comment by scullxbones** [comment]
Hi @barakbn 

The plugin just tails the capped collection, rather than querying it - so from that perspective an index would just slow inserts down with no query advantage.  That said, the only "by-design" I can claim is not expressly including any index, I didn't know that there was no `_id` index.

It does look like replication of the capped collection is lost, which I didn't realize.  That's probably OK, given what it's being used for - basically a message bus for all persistent events going through the plugin.
