### ISSUE TITLE
EventAdapter has no effect on receiveRecover (fromJournal method is not called)

### ISSUE THREAD

**Issue by wenhuancui** [scullxbones/akka-persistence-mongo#173]
As the title says, events stored as BSONDocument cannot be 'automatically' converted back (pattern matching on event type is failing). And log shows that fromJournal method is not called. However, toJournal method of the EventAdapter is definitely called, as confirmed in the corresponding mongodb collection.
Version info is as follows:
        <dependency>
            <groupId>com.github.scullxbones</groupId>
            <artifactId>akka-persistence-mongo-rxmongo_2.12</artifactId>
            <version>2.0.3</version>
        </dependency>

**Comment by scullxbones** [comment]
Hi @wenhuancui 

The event adapter is outside of the control of persistence plugins such as this one, it's used entirely by the `akka-persistence` layer.  I'm confused as to what you're reporting as far as an issue for this plugin to address.  

What may be the problem is that the `event-adapter-bindings` need to be specified in both directions.  In other words, there should be a mention of `BSONDocument`, linking it to your `EventAdapter` implementation, in addition to whatever scala class you're using to model your events (or sealed trait).  Without any code, it's hard to say for sure.

I'd say you could refer to #165 - but there's not much to go on there, other than EventAdapter has worked for others.  I also have it working at my day job as part of a continuous test suite.

**Comment by wenhuancui** [comment]
Thanks @scullxbones. I had read the link #165, and yes it has little information, so I stumbled on this matter. Your clarifications are great for a newbie like me, especially this one: "The event adapter is outside of the control of persistence plugins...there should be a mention of BSONDocument" .
So I changed the configuration and it worked like a charm:
akka-contrib-mongodb-persistence-journal {
  event-adapters{
    luckyEventAdded =
      "com.learnscala.explore.akka.persistence.lottery.LuckyEventAdapter"
  }
  event-adapter-bindings{
    "com.learnscala.explore.akka.persistence.lottery.LuckyEvent"=luckyEventAdded
    "reactivemongo.bson.BSONDocument"=luckyEventAdded
  }
}

The key is the last line. Thanks again.
P.S.  Maybe adding such clarifications to the docs can keep other newbies from this mistake?

**Comment by scullxbones** [comment]
That's great news - happy to help out 👍

**Comment by scullxbones** [comment]
Added #174 to track the docs change.

**Comment by asarkar** [comment]
+1 @wenhuancui. https://github.com/scullxbones/akka-persistence-mongo/issues/165 is a contender for the worst GitHub issue for the year ("Got it working, sorry." - really, wtf?), your description helped me.
