### ISSUE TITLE
EventByTag query queries all collections in database

### ISSUE THREAD

**Issue by scullxbones** [scullxbones/akka-persistence-mongo#195]
* Queries try to find by tag field with sort.
* Queries done in `EventByTag` function using `driver.getAllCollection`

**Comment by Fabszn** [comment]
Hi,

I see in mongoDb logs the following kind of queries : 

`"_tg": "[tag name]$",
   "_id": {
     "$gt": {
       "$oid": "5b6b75066d1502773ae10c00"
     }
   }`

**[tag name]* -> is not the real value**

This query is applied on every collections existing in my mongoDB database. 

I  dived myself into akka persistence mongo code, and I see this piece of code that let me guess that the lib get all collection names from DB, and run the query (above) on every collection found (excepted system collection and realtime collection. 

https://github.com/scullxbones/akka-persistence-mongo/blob/5c37f7e7c832bd0aaf1ee7ffb4d6eed2763f932f/rxmongo/src/main/scala/akka/contrib/persistence/mongodb/RxMongoReadJournaller.scala#L119

with the function : `driver.getAllCollectionsAsFuture(None)`

From my understanding, it should great to filter collections for just get the akka persistence mongo collections. Currently, lot queries traffic is generated.

Or I miss something. 

Many thanks for your help

**Comment by Fabszn** [comment]
Hi @scullxbones 

I saw your PR. It's cool. 
I looked at changes that you done by your PR. If I understood right, the change make here : 
https://github.com/scullxbones/akka-persistence-mongo/blob/292073bbbc9b7111b80d04e0c187f8a452fbf69a/rxmongo/src/main/scala/akka/contrib/persistence/mongodb/RxMongoReadJournaller.scala#L119
will fix the issue that I notified ? 
If I am right, I will make an intermediate version (generate by my self) until the new release version will be done. 
In fact, I really need this fix because there is to much queries on event tag executed  and DB performance are impacted. 

Again many thanks for your help and your reactivity

**Comment by scullxbones** [comment]
@Fabszn - yep the actual fix is quite small.  Most of the rest is me trying to get travis to build correctly and the tests to complete.  There's some network issue happening that the travis team thought was fixed Friday, but apparently has returned.  Will update this ticket when I can finally release.

**Comment by Fabszn** [comment]
Many thanks

**Comment by scullxbones** [comment]
Sorry it took so long to get a release out, but it's out in `2.0.11` - thanks for reporting!

**Comment by Fabszn** [comment]
No worries :-)

Many thanks for your reactivity ! I will update my project with the new release.
