### ISSUE TITLE
Using a custom SuffixBuilder class throws ClassNotFoundException in Play project in dev mode

### ISSUE THREAD

**Issue by Woodz** [scullxbones/akka-persistence-mongo#227]
Reproduction steps:
- Create a Play 2.6 project that uses akka-persistence-mongo
- Create a class to be used for providing Mongo collection suffixes and configure as per
https://github.com/scullxbones/akka-persistence-mongo/blob/master/docs/akka25.md#configuration
- Try to run the application in dev mode

Expected: The class is loaded and called
Actual: `ClassNotFoundException` thrown

Investigation: The ClassLoader used to load is for `sbt-launcher.jar` which is a very restricted ClassLoader and has no access to application code

**Comment by scullxbones** [comment]
Hi @Woodz -

Thanks for the PR!  Good catch on the classloader issues.  I know i've run into those using Play in dev mode in the past.

I'd prefer to leverage the akka way and use `DynamicAccess` here which is a utility API available on `ExtendedActorSystem`.  We use it today to load the driver-specific parts of the plugin.  The fix is mainly just carrying the extended parameter type through, then using `DynamicAccess` to load the class.

**Comment by scullxbones** [comment]
> I know i've run into those using Play in dev mode in the past.

In other projects of course, I've never seen this specific error before :)

**Comment by scullxbones** [comment]
Fixed with `2.2.5` - thanks for the report!
